# gokapi-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gokapi-config
data:
  cloudconfig.yml.template: |
    aws:
      Bucket: ${AWS_BUCKET}
      Region: ${AWS_REGION}
      KeyId: ${AWS_KEY_ID}
      KeySecret: ${AWS_KEY_SECRET}
      Endpoint: ""
      ProxyDownload: false
  config.json.template: |
    {
      "Authentication": {
        "Method": 0,
        "SaltAdmin": "${AUTH_SALT_ADMIN}",
        "SaltFiles": "${AUTH_SALT_FILES}",
        "Username": "${AUTH_USERNAME}",
        "Password": "${AUTH_PASSWORD}",
        "HeaderKey": "",
        "OauthProvider": "",
        "OAuthClientId": "",
        "OAuthClientSecret": "",
        "OauthUserScope": "",
        "OauthGroupScope": "",
        "OAuthRecheckInterval": 12,
        "HeaderUsers": null,
        "OAuthGroups": [],
        "OauthUsers": []
      },
      "Port": ":53842",
      "ServerUrl": "https://file.andex.tokyo/",
      "RedirectUrl": "/admin",
      "PublicName": "andex File Transer",
      "DataDir": "data",
      "DatabaseUrl": "sqlite://./data/gokapi.sqlite",
      "ConfigVersion": 21,
      "LengthId": 15,
      "MaxFileSizeMB": 102400,
      "MaxMemory": 50,
      "ChunkSize": 45,
      "MaxParallelUploads": 4,
      "Encryption": {
        "Level": 0,
        "Cipher": null,
        "Salt": "",
        "Checksum": "",
        "ChecksumSalt": ""
      },
      "UseSsl": false,
      "PicturesAlwaysLocal": false,
      "SaveIp": false,
      "IncludeFilename": false
    }
